#!/bin/sh
#

BASEDIR=$(dirname $0)

if [ -z $1 ]; then
  echo usage $0 "<platform>"
  exit 1
fi

PLATFORM=$1

ln -sf ./Makefile.$PLATFORM $BASEDIR/ecp/Makefile.platform
ln -sf ./config_$PLATFORM.h $BASEDIR/ecp/config.h