#define IRQ_PRIORITY_I2S_SD     7
#define IRQ_PRIORITY_I2S_WS     6

#define IRQ_PRIORITY_SPI_XCHG   5

#define IRQ_PRIORITY_NET_CTS    4
#define IRQ_PRIORITY_NET_RTS    4

#define IRQ_PRIORITY_UART       1